machine_tool:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  x_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: x_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  y_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: y_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  r_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: r_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}